---
- name: Configure MySQL Server
  hosts: dbserver
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Start MySQL Service
      service:
        name: mysql
        state: started

    - name: Update MySQL Configuration
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "^(bind-address|mysqlx-bind-address)\\s*=\\s*127.0.0.1$"
        replace: "\\1 = 0.0.0.0"

    - name: Reload Systemd
      shell: systemctl daemon-reload

    - name: "Install ansible python3 mysql dependency"
      apt:
        name: python3-mysqldb
        state: latest    
    
    - name: Restart MySQL Service
      service:
        name: mysql
        state: restarted

    - name: Create MySQL User
      mysql_user:
        name: nop
        host: "%"
        password: nop12345
        priv: "*.*:ALL,GRANT"


