---
- name: Configure MySQL Server
  hosts: nopserver
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Start MySQL Service
      service:
        name: mysql
        state: started

    - name: Update MySQL Configuration
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "^(bind-address|mysqlx-bind-address)\\s*=\\s*127.0.0.1$"
        replace: "\\1 = 0.0.0.0"

    - name: Reload Systemd
      shell: systemctl daemon-reload

    - name: Install MySQL Module for Python 2.7
      pip:
        name: pymysql
      when: python_version.stdout == "2"

    - name: Install MySQL Module for Python 3.x
      pip:
        name: mysqlclient
      when: python_version.stdout == "3"
      
    - name: Restart MySQL Service
      service:
        name: mysql
        state: restarted

    - name: Create MySQL User
      mysql_user:
        name: nop
        host: "%"
        password: nop12345
        priv: "*.*:ALL,GRANT"

    - name: Flush MySQL Privileges
      mysql_db:
        login_user: devops
        login_password: devops
        name: "*.*"
        state: flush_privileges
