---
- name: Setup nopCommerce
  hosts: nopserver  # Replace with your target host or group
  become: yes  # Become a superuser for privileged tasks

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name:
          - unzip
          - apt-transport-https
          - aspnetcore-runtime-7.0
        state: present
        update_cache: yes

    - name: Download and extract nopCommerce
      become_user: your_username  # Replace with your username
      shell: |
        cd /var/nopCommerce
        wget https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.4/nopCommerce_4.60.4_NoSource_linux_x64.zip
        unzip nopCommerce_4.60.4_NoSource_linux_x64.zip
        mkdir bin logs

    - name: Create nop user
      user:
        name: nop
        state: present

    - name: Grant full permissions to nop user on /var/nopCommerce
      file:
        path: /var/nopCommerce
        owner: nop
        group: nop
        recurse: yes

    - name: Create nopCommerce systemd service
      copy:
        dest: /etc/systemd/system/nopCommerce.service
        content: |
          [Unit]
          Description=Example nopCommerce app running on Ubuntu

          [Service]
          WorkingDirectory=/var/nopCommerce
          ExecStart=/usr/bin/dotnet /var/nopCommerce/Nop.Web.dll --urls "http://0.0.0.0:5000"
          Restart=always
          RestartSec=10
          KillSignal=SIGINT
          SyslogIdentifier=nopCommerce-example
          User=nop
          Environment=ASPNETCORE_ENVIRONMENT=Production
          Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start the nopCommerce service
      systemd:
        name: nopCommerce
        enabled: yes
        state: started
