---
- name: Setup nopCommerce
  hosts: nopserver # Replace with your target host(s)
  become: yes

  tasks:
    - name: Update Ubuntu packages
      apt:
        update_cache: yes

    - name: Download and extract nopCommerce
      shell: |
        cd /tmp
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y apt-transport-https aspnetcore-runtime-7.0
        dotnet --list-runtimes
        sudo apt install unzip -y
        sudo mkdir /var/nopCommerce
        cd /var/nopCommerce
        sudo wget https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.4/nopCommerce_4.60.4_NoSource_linux_x64.zip
        sudo unzip nopCommerce_4.60.4_NoSource_linux_x64.zip
        sudo mkdir bin logs

    - name: Run nopCommerce
      shell: sudo dotnet /var/nopCommerce/Nop.Web.dll --urls "http://0.0.0.0:5000"
      async: 0
      poll: 0

    - name: Grant full permissions to devops user on /var/nopCommerce
      file:
        path: /var/nopCommerce
        owner: devops
        group: devops
        recurse: yes

    - name: Create nopCommerce systemd service
      copy:
        dest: /etc/systemd/system/nopCommerce.service
        content: |
          [Unit]
          Description=Example nopCommerce app running on Xubuntu

          [Service]
          WorkingDirectory=/var/nopCommerce
          ExecStart=/usr/bin/dotnet /var/nopCommerce/Nop.Web.dll --urls "http://0.0.0.0:5000"
          Restart=always
          RestartSec=10
          KillSignal=SIGINT
          SyslogIdentifier=nopCommerce-example
          User=devops
          Environment=ASPNETCORE_ENVIRONMENT=Production
          Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start the nopCommerce service
      systemd:
        name: nopCommerce
        enabled: yes
        state: started

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
